version: "3.9"

services:
  lawn-mower-db:
    image: postgres:latest
    container_name: lawn-mower-db
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'root']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - lawn-mower-database:/var/lib/postgresql/data
    networks:
      - lawn-mower-backend

volumes:
  lawn-mower-database:

networks:
  lawn-mower-backend:
