name: Test And Lint Code
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - ".husky/**"
      - ".dockerignore"
      - ".gitignore"
      - "*.todo"
  pull_request:
    paths-ignore:
      - "*.md"
      - ".vscode/**"
      - ".husky/**"
      - ".dockerignore"
      - ".gitignore"
      - "*.todo"
  workflow_dispatch:

jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.ref_name != 'develop' && github.ref_name != 'main'
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0

  catalog-service-test:
    name: Lint And Test Catalog Service (Golang)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: apps/catalog-service/go.mod

      - name: Linting
        uses: docker://morphy/revive-action:v2

      - name: Test
        run: |
          cd apps/catalog-service
          make coverage-ci
          cat coverage.out

      - name: Build
        run: |
          cd apps/catalog-service
          make all

      - uses: jandelgado/gcov2lcov-action@v1
        with:
          infile: coverage.out # optional, default filename is `coverage.out`
          outfile: coverage.lcov # optional, default filename is `coverage.lcov`
          working-directory: apps/catalog-service # optional, change working directory

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: apps/catalog-service/coverage.lcov
          language: Go
